import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const content = JSON.parse(await readFile(new URL('../../content/seminars.json', import.meta.url), 'utf8'));

for (const [randomValue, imageName] of [[0.25, 'whu-enhanced.png'], [0.75, 'ccnu-autumn-enhanced.png']]) {
  test(`campus background selects ${imageName} and stays stable while browsing`, async ({ page }) => {
    await page.addInitScript(value => { Math.random = () => value; }, randomValue);
    await page.goto('/');
    await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
    const surface = page.locator('.public-page');
    await expect(surface).toHaveCSS('background-image', new RegExp(imageName.replace('.', '\\.')));
    const initialBackground = await surface.evaluate(element => getComputedStyle(element).backgroundImage);
    const asset = await page.request.get(`/images/${imageName}`);
    expect(asset.ok()).toBe(true);
    expect(asset.headers()['content-type']).toMatch(/^image\//);
    // A later render must not choose a different campus.
    await page.evaluate(value => { Math.random = () => value; }, 1 - randomValue);
    await page.getByLabel('按年份筛选').selectOption('2025');
    await expect(page.locator('article.talk')).toHaveCount(1);
    await page.getByRole('button', { name: /摘要/ }).click();
    await expect(page.locator('.abstract-text')).toBeVisible();
    await expect(surface).toHaveCSS('background-image', initialBackground);
    await page.getByRole('button', { name: '清除筛选 ×' }).click();
    await expect(surface).toHaveCSS('background-image', initialBackground);
  });
}

test('archive renders every source record, filters months and shows only real attachments', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1080 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
  await expect(page.locator('.site-header, .archive-sidebar, .archive-title-row, .about-heading')).toHaveCount(0);
  await page.locator('article.talk').filter({ hasText: 'Yann Bugeaud' }).screenshot({ path: 'C:/Users/cimorn/AppData/Local/Temp/seminar-metadata-icons-desktop.png' });
  await expect(page.getByRole('button', { name: '刷新内容' })).toHaveCount(0);
  const attached = content.talks.reduce((n, talk) => n + talk.attachments.length, 0);
  await expect(page.locator('.attachment-link')).toHaveCount(attached);
  const long = [...content.talks].sort((a, b) => (b.abstract?.length || 0) - (a.abstract?.length || 0))[0];
  const abstract = page.locator(`[id="${long.id}"] .talk-abstract`);
  await expect(abstract.locator('.abstract-text')).toBeHidden();
  await abstract.getByRole('button', { name: /摘要/ }).click();
  await expect(abstract.locator('.abstract-text')).toBeVisible();
  await expect(abstract.locator('.abstract-text')).not.toHaveCSS('-webkit-line-clamp', /[1-9]/);
  await abstract.getByRole('button', { name: /摘要/ }).focus();
  await page.keyboard.press('Enter');
  await expect(abstract.locator('.abstract-text')).toBeHidden();
  await expect(page.locator('.seminar-intro .organizer')).toHaveCount(content.site.organizers.length);
  await expect(page.getByRole('button', { name: '关于', exact: true })).toBeHidden();
  await expect(page.locator('.seminar-venue-note')).toBeVisible();
  await expect(page.locator('.seminar-venue-note')).toHaveText('The talks will take place at Wuhan University and Central China Normal University in turn.');
  const aboutBox = await page.locator('.seminar-intro').boundingBox();
  const archiveBox = await page.locator('#archive').boundingBox();
  expect(aboutBox.y + aboutBox.height).toBeLessThanOrEqual(archiveBox.y);
  await expect(page.getByRole('img', { name: '科赫雪花曲线' })).toBeVisible();
  await expect(page.locator('.public-page')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await expect(page.locator('.archive-facts, .sidebar-note, .back-top, .talk-notes, .source-link')).toHaveCount(0);
  await expect(page.getByRole('link', { name: /原始记录/ })).toHaveCount(0);
  await expect(page.getByRole('link', { name: '关于讨论班' })).toHaveCount(0);
  await page.getByLabel('按年份筛选').selectOption('2025');
  await page.getByLabel('按月份筛选').selectOption('09');
  await expect(page.locator('article.talk')).toHaveCount(content.talks.filter(t => t.date.startsWith('2025-09')).length);
  await page.getByLabel('按月份筛选').selectOption('01');
  await expect(page.getByRole('heading', { name: '没有找到符合条件的报告' })).toBeVisible();
  await page.getByRole('button', { name: '清除筛选' }).click();
  await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
  await page.evaluate(() => window.scrollTo(0, 400));
  await expect.poll(async () => (await page.locator('.floating-filters').boundingBox()).y).toBeCloseTo(16, 0);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/archive-desktop.png', fullPage: false });
  expect(errors).toEqual([]);
});

for (const width of [390, 834]) {
  test(`about information opens from the floating button at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 });
    await page.goto('/');
    await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
    const toggle = page.getByRole('button', { name: '关于', exact: true });
    const panel = page.getByRole('region', { name: '关于讨论班', exact: true });
    await expect(toggle).toBeVisible();
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    await expect(page.locator('.organizers')).toBeHidden();
    const position = await toggle.boundingBox();
    expect(position.x + position.width).toBeGreaterThan(width - 40);
    expect(position.y + position.height).toBeGreaterThan(804);
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    await expect(panel).toBeVisible();
    for (const person of content.site.organizers) {
      await expect(panel.getByText(person.name, { exact: true })).toBeVisible();
      await expect(panel.getByRole('link', { name: person.email, exact: true })).toHaveAttribute('href', `mailto:${person.email}`);
    }
    await expect(panel).toContainText('The talks will take place at Wuhan University and Central China Normal University in turn.');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    await page.screenshot({ path: `test-results/about-${width}.png`, fullPage: false });
    await panel.getByRole('link').first().focus();
    await page.keyboard.press('Escape');
    await expect(panel).toBeHidden();
    await expect(toggle).toBeFocused();
    await toggle.press('Enter');
    await expect(panel).toBeVisible();
    await page.locator('.intro-copy').click();
    await expect(panel).toBeHidden();
    await toggle.click();
    await toggle.click();
    await expect(panel).toBeHidden();
    await page.setViewportSize({ width: 1440, height: 1080 });
    await expect(toggle).toBeHidden();
    await expect(panel).toBeVisible();
    await expect(page.locator('.organizers')).toBeVisible();
  });
}

test('public and administrator mobile layouts fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
  await expect(page.getByLabel('按月份筛选')).toBeVisible();
  await expect(page.getByLabel('按年份筛选')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.locator('article.talk').filter({ hasText: 'Yann Bugeaud' }).screenshot({ path: 'C:/Users/cimorn/AppData/Local/Temp/seminar-metadata-icons-mobile.png' });
  await page.screenshot({ path: 'test-results/archive-mobile.png', fullPage: false });
  await page.goto('/admin.html');
  await page.getByLabel('管理员密码').fill('test-only-not-a-production-password');
  await page.getByRole('button', { name: '登录管理后台' }).click();
  await expect(page.getByLabel('后台按年份筛选')).toBeHidden();
  await page.getByRole('button', { name: '年份 / 月份 / 日期', exact: true }).click();
  await expect(page.getByLabel('后台按年份筛选')).toBeVisible();
  await expect(page.getByLabel('筛选开始日期')).toBeVisible();
  await page.locator('.admin-record').first().click();
  await expect(page.getByLabel('链接', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.locator('.admin-editor').screenshot({ path: 'C:/Users/cimorn/AppData/Local/Temp/seminar-admin-compact-form-390.png' });
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: false });
});

for (const width of [390, 834]) {
  test(`administrator filters collapse and preserve selections at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 });
    await page.goto('/admin.html');
    await page.getByLabel('管理员密码').fill('test-only-not-a-production-password');
    await page.getByRole('button', { name: '登录管理后台' }).click();
    await expect(page.getByRole('link', { name: '讨论班主页', exact: true })).toHaveAttribute('href', '/');
    await expect(page.getByRole('img', { name: 'a · p 讨论班 logo', exact: true })).toBeVisible();
    await page.locator('.admin-header').screenshot({ path: `C:/Users/cimorn/AppData/Local/Temp/seminar-admin-logo-header-${width}.png` });
    const toggle = page.getByRole('button', { name: '年份 / 月份 / 日期', exact: true });
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    await expect(page.getByLabel('后台按年份筛选')).toBeHidden();
    await expect(page.getByLabel('筛选开始日期')).toBeHidden();
    await expect(page.locator('.admin-list-instruction')).toHaveText('点击编辑');
    await expect(page.locator('.admin-list-instruction')).toBeVisible();
    await page.screenshot({ path: `C:/Users/cimorn/AppData/Local/Temp/seminar-admin-filters-${width}-collapsed.png`, fullPage: false });
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    await page.screenshot({ path: `C:/Users/cimorn/AppData/Local/Temp/seminar-admin-filters-${width}-expanded.png`, fullPage: false });
    await page.getByLabel('后台按年份筛选').selectOption('2025');
    await page.getByLabel('后台按月份筛选').selectOption('09');
    await page.getByLabel('筛选开始日期').fill('2025-09-01');
    await page.getByLabel('筛选结束日期').fill('2025-09-30');
    await expect(page.locator('.admin-record')).toHaveCount(1);
    await toggle.click();
    await expect(page.getByLabel('后台按年份筛选')).toBeHidden();
    await expect(page.locator('.admin-record')).toHaveCount(1);
    await toggle.click();
    await expect(page.getByLabel('后台按年份筛选')).toHaveValue('2025');
    await expect(page.getByLabel('筛选结束日期')).toHaveValue('2025-09-30');
    await page.getByRole('button', { name: '清除筛选', exact: true }).click();
    await expect(page.locator('.admin-record')).toHaveCount(content.talks.length);
    await toggle.click();
    await page.locator('.admin-record').filter({ hasText: 'Maria Loukaki' }).click();
    await expect(page.getByRole('heading', { name: '编辑报告', exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    await page.locator('.admin-editor').screenshot({ path: `C:/Users/cimorn/AppData/Local/Temp/seminar-admin-compact-form-${width}.png` });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await expect(toggle).toBeHidden();
    await expect(page.getByLabel('后台按年份筛选')).toBeVisible();
    await expect(page.getByLabel('筛选开始日期')).toBeVisible();
    await expect(page.locator('.admin-list-instruction')).toBeHidden();
    await page.locator('.admin-header').screenshot({ path: 'C:/Users/cimorn/AppData/Local/Temp/seminar-admin-logo-header-desktop.png' });
  });
}

test('fractal opens the password-protected management page in a separate tab', async ({ page }) => {
  await page.goto('/');
  const popupPromise = page.waitForEvent('popup');
  await page.getByRole('link', { name: '打开管理页面（新窗口）' }).click();
  const popup = await popupPromise;
  await expect(popup.getByLabel('管理员密码')).toBeVisible();
  await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
  await popup.close();
});

test('only the report title opens its meeting link, with independent abstract and handout controls', async ({ page, context }) => {
  const firstTalk = [...content.talks].sort((a, b) => b.date.localeCompare(a.date))[0];
  const meetingUrl = firstTalk.sourceUrls[0];
  await context.route(meetingUrl, route => route.fulfill({ contentType: 'text/html', body: '<h1>Meeting destination</h1>' }));
  await page.goto('/');
  const card = page.locator('article.talk').first();
  await expect(card.locator('.talk-title')).toHaveCSS('color', 'rgb(20, 126, 150)');
  await card.getByRole('button', { name: /摘要/ }).click();
  await expect(card.locator('.abstract-text')).toBeVisible();
  expect(context.pages()).toHaveLength(1);
  await card.click({ position: { x: 12, y: 12 } });
  await card.locator('.talk-speaker').click();
  expect(context.pages()).toHaveLength(1);
  await expect(page).toHaveURL('http://127.0.0.1:5187/');
  await expect(card.locator('.talk-title-link')).toHaveAttribute('href', meetingUrl);
  const popupPromise = page.waitForEvent('popup');
  await card.locator('.talk-title-link').click();
  const popup = await popupPromise;
  await expect(popup.getByRole('heading', { name: 'Meeting destination' })).toBeVisible();
  expect(popup.url()).toBe(meetingUrl);
  await popup.close();
  const attachment = page.locator('.attachment-link').first();
  await expect(attachment).toHaveText('PDF');
  const handoutCard = page.locator('article.talk').filter({ has: attachment }).first();
  await expect(handoutCard.getByRole('button', { name: /摘要/ })).toHaveAttribute('aria-expanded', 'false');
  const attachmentUrl = new URL(await attachment.getAttribute('href'), page.url()).href;
  const filePopupPromise = page.waitForEvent('popup');
  await attachment.click();
  const filePopup = await filePopupPromise;
  await expect(filePopup).toHaveURL(attachmentUrl);
  await expect(filePopup.locator('canvas').first()).toBeVisible();
  await filePopup.close();
  await expect(handoutCard.getByRole('button', { name: /摘要/ })).toHaveAttribute('aria-expanded', 'false');
});

test('an imported PDF renders real pages and thumbnails', async ({ page }) => {
  const file = content.talks.flatMap(t => t.attachments).find(a => a.name === 'LUO_Jun.pdf') || content.talks.flatMap(t => t.attachments).find(a => a.type === 'pdf' && a.path);
  expect(file).toBeTruthy();
  await page.goto(`/viewer.html?file=${encodeURIComponent('/' + file.path)}&name=${encodeURIComponent(file.name)}`);
  await expect(page.locator('canvas').first()).toBeVisible({ timeout: 30_000 });
  await expect.poll(() => page.locator('canvas').count()).toBeGreaterThan(1);
  await expect(page.locator('.pdf-page').first().locator('.page-loading')).toHaveCount(0);
  await expect(page.locator('.thumbnail-button').nth(1).locator('.page-loading')).toHaveCount(0);
  await page.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(page.getByLabel('页码', { exact: true })).toHaveValue('2');
  await page.getByLabel('缩放方式').selectOption('actual');
  await expect(page.getByLabel('页码', { exact: true })).toHaveValue('2');
  await expect(page.locator('.viewer-error')).toHaveCount(0);
  await page.getByRole('button', { name: '上一页', exact: true }).click();
  await expect(page.getByLabel('页码', { exact: true })).toHaveValue('1');
  await expect(page.locator('.pdf-page').first().locator('.page-loading')).toHaveCount(0);
  await page.screenshot({ path: 'test-results/pdf-viewer.png', fullPage: false });
});

test('admin publishes full records, uploads actual multipart PDF and updates archive without a build', async ({ page, context }) => {
  await page.goto('/admin.html');
  await page.getByLabel('管理员密码').fill('test-only-not-a-production-password');
  await page.getByRole('button', { name: '登录管理后台' }).click();
  await expect(page.getByRole('navigation', { name: '后台导航' }).getByRole('button', { name: '新建报告', exact: true })).toBeVisible();
  await expect(page.locator('.editor-empty').getByRole('button', { name: '新建报告', exact: true })).toBeVisible();
  await expect(page.locator('.admin-record')).toHaveCount(content.talks.length);
  await page.getByLabel('后台按年份筛选').selectOption('2026');
  await expect(page.locator('.admin-record')).toHaveCount(2);
  await page.getByLabel('后台按月份筛选').selectOption('04');
  await expect(page.locator('.admin-record')).toHaveCount(1);
  await expect(page.locator('.admin-record')).toContainText('Yann Bugeaud');
  await page.getByRole('button', { name: '清除筛选', exact: true }).click();
  await page.getByLabel('筛选开始日期').fill('2024-10-24');
  await page.getByLabel('筛选结束日期').fill('2025-09-09');
  await expect(page.locator('.admin-record')).toHaveCount(2);
  await page.getByRole('button', { name: '清除筛选', exact: true }).click();
  await page.locator('.editor-empty').getByRole('button', { name: '新建报告', exact: true }).click();
  await expect(page.getByLabel('补充说明')).toHaveCount(0);
  await expect(page.getByLabel('链接', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '附件上传', exact: true })).toBeVisible();
  const title = '浏览器测试：Full report and attachment';
  const renamedName = '261004_本地测试报告人_浏览器测试-Full report and attachment.pdf';
  await page.getByLabel('报告标题').fill(title);
  await page.getByLabel('报告人', { exact: false }).fill('本地测试报告人');
  await page.getByLabel('单位', { exact: true }).fill('测试大学/Test University');
  await expect(page.locator('input[type="time"]')).toHaveCount(2);
  await page.getByLabel('开始时间', { exact: true }).fill('10:15');
  await expect(page.getByLabel('结束时间', { exact: true })).toHaveValue('11:15');
  await page.getByLabel('结束时间', { exact: true }).fill('11:45');
  await page.getByRole('combobox', { name: '举办学校', exact: true }).selectOption('华师');
  await page.getByLabel('具体地点', { exact: true }).fill('测试报告厅');
  await page.locator('.editor-fields').getByLabel('日期', { exact: false }).fill('2026-10-04');
  await page.getByLabel('完整摘要').fill('第一段完整摘要。\n\n第二段：应完整显示在公开页面。');
  await page.getByLabel('链接', { exact: true }).fill('https://example.com/seminar');
  await page.getByLabel('后台按年份筛选').selectOption('2023');
  await expect(page.getByLabel('报告标题')).toHaveValue(title);
  await expect(page.getByLabel('完整摘要')).toHaveValue(/第二段/);
  await page.getByRole('button', { name: '清除筛选', exact: true }).click();
  await page.getByLabel('结束时间', { exact: true }).fill('10:15');
  await expect(page.getByRole('alert')).toContainText('结束时间必须晚于开始时间');
  await expect(page.getByRole('button', { name: '保存报告', exact: true })).toBeDisabled();
  await page.getByLabel('结束时间', { exact: true }).fill('10:00');
  await expect(page.getByRole('alert')).toContainText('结束时间必须晚于开始时间');
  await page.getByLabel('开始时间', { exact: true }).fill('10:30');
  await expect(page.getByLabel('结束时间', { exact: true })).toHaveValue('11:30');
  await page.getByLabel('开始时间', { exact: true }).fill('10:15');
  await expect(page.getByLabel('结束时间', { exact: true })).toHaveValue('11:15');
  await page.getByLabel('结束时间', { exact: true }).fill('11:45');
  await page.getByRole('button', { name: '保存报告', exact: true }).click();
  await expect(page.locator('.notice.success')).toContainText('已保存');
  const archive = await context.newPage();
  await archive.goto('/');
  const card = archive.locator('article.talk').filter({ has: archive.getByRole('heading', { name: title }) });
  await expect(card).toBeVisible();
  await expect(card).toContainText('华师 · 测试报告厅');
  await expect(card).toContainText('测试大学/Test University');
  await expect(card).toContainText('2026-10-04 10:15-11:45');
  await page.reload();
  await page.locator('.admin-record').filter({ hasText: title }).click();
  await expect(page.getByLabel('单位', { exact: true })).toHaveValue('测试大学/Test University');
  await expect(page.getByLabel('开始时间', { exact: true })).toHaveValue('10:15');
  await expect(page.getByLabel('结束时间', { exact: true })).toHaveValue('11:45');
  await page.locator('.field-grid').screenshot({ path: 'C:/Users/cimorn/AppData/Local/Temp/seminar-admin-bilingual-time.png' });
  await expect(card.locator('.talk-title-link')).toHaveAttribute('href', 'https://example.com/seminar');
  await expect(card.locator('.attachment-link')).toHaveCount(0);
  await expect(card.locator('.abstract-text')).toBeHidden();
  await card.getByRole('button', { name: /摘要/ }).click();
  await expect(card.locator('.abstract-text')).toBeVisible();
  await expect(card).toContainText('第二段：应完整显示在公开页面。');
  const files = content.talks.flatMap(t => t.attachments).filter(a => a.type === 'pdf' && a.path);
  const file = files.find(a => a.size > 2 * 1024 * 1024) || files[0];
  await page.getByLabel('附件上传', { exact: true }).setInputFiles(fileURLToPath(new URL('../../' + file.path, import.meta.url)));
  await expect(page.locator('.notice.success')).toContainText('文件已上传', { timeout: 30_000 });
  await expect(page.locator('.attachment-list strong')).toHaveText(renamedName);
  await page.getByRole('button', { name: '保存报告', exact: true }).click();
  await expect(page.locator('.notice.success')).toContainText('已保存');
  await archive.reload();
  await expect(card.locator('.attachment-link')).toHaveCount(1);
  const viewerUrl = new URL(await card.locator('.attachment-link').getAttribute('href'), 'http://127.0.0.1:5187');
  expect(viewerUrl.searchParams.get('name')).toBe(renamedName);
  const attachedFile = await page.request.get(viewerUrl.searchParams.get('file'));
  expect(attachedFile.ok()).toBe(true);
  expect(await attachedFile.body()).toEqual(await readFile(new URL('../../' + file.path, import.meta.url)));
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/admin-editor.png', fullPage: false });
  await page.getByRole('button', { name: '删除报告', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await expect(page.locator('.notice.success')).toContainText('报告记录已删除');
  await archive.reload();
  await expect(archive.locator('article.talk')).toHaveCount(content.talks.length);
  await page.getByRole('link', { name: '返回主页', exact: true }).click();
  await expect(page).toHaveURL('http://127.0.0.1:5187/');
  await expect(page.locator('article.talk')).toHaveCount(content.talks.length);
  await page.goto('/admin.html');
  await expect(page.getByRole('navigation', { name: '后台导航' }).getByRole('button', { name: '新建报告', exact: true })).toBeVisible();
  await archive.close();
});
